/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class taskbar_Taskbar */

#ifndef _Included_taskbar_Taskbar
#define _Included_taskbar_Taskbar
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     taskbar_Taskbar
 * Method:    setProgressState
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_taskbar_Taskbar_setProgressState
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
